### ISSUE TITLE
Is gene perturbation metadata currently available? (cpg0016-jump)

### ISSUE THREAD

**Issue by nmra-abarthmaron** [jump-cellpainting/datasets#11]
Hi Team!

This data looks fantastic, and I can't wait to dig deeper into it. I read the advisory stating that cpg0016 is still a work in progress, as well as seeing the 'First draft of metadata files' bullet under 'What's available now'. From perusing the metadata I found 15,133 unique `Metadata_JCP2022` values in the `well` table that are not in the `compound` table, so I am assuming that these are the gene perturbations, is that correct? If so, my main question is - is there metadata (either in the form of another table, or individual platemap CSVs) for these conditions yet?

Apologies if the answer is just that it will be coming in future updates, and I'm just being too over-eager.

Thanks a lot!

Best,
Asa Barth-Maron

**Comment by niranjchandrasekaran** [comment]
Hello @nmra-abarthmaron, thank you for your interest in our dataset! 

> so I am assuming that these are the gene perturbations, is that correct?

That's correct. The missing `JCP2022 ID`s correspond to the genes that were overexpressed (using ORFs).

> If so, my main question is - is there metadata (either in the form of another table, or individual platemap CSVs) for these conditions yet?

We are working on generating another table for the ORF dataset, and it will be available soon.

> and I'm just being too over-eager.

It is exciting that you have already begun digging into the data :)

**Comment by nmra-abarthmaron** [comment]
Hi @niranjchandrasekaran. Thank you so much for the prompt reply! 

> We are working on generating another table for the ORF dataset, and it will be available soon.
Great!

> It is exciting that you have already begun digging into the data :)
:)

**Comment by shntnu** [comment]
> We are working on generating another table for the ORF dataset,

All set!

See `orf.csv.gz` here: https://github.com/jump-cellpainting/datasets/tree/main/metadata

**Comment by nmra-abarthmaron** [comment]
Fantastic, thank you!!

**Comment by shntnu** [comment]
> `orf.csv.gz` here: https://github.com/jump-cellpainting/datasets/tree/main/metadata

and so is `crispr.csv.gz` now
