### ISSUE TITLE
update "Does JUMP contain X compound/gene?" link on FAQ

### ISSUE THREAD

**Issue by AnneCarpenter** [jump-cellpainting/datasets#110]
On [this page](https://broadinstitute.github.io/2023_12_JUMP_data_only_vignettes/explanations/FAQ.html) it says 
Data

Does JUMP contain X compound/gene?
We have done our best to ensure that if you can check if your compound is available [here](https://github.com/jump-cellpainting/datasets/issues).

but that URL just goes to the issues of this repo rather than a place to check for your compound/gene.

(side note: typo in "Frequently Asqued Questions" in the sidebar -> Asked)

**Comment by AnneCarpenter** [comment]
Also wanted to check whether the code here points to the latest JUMP recommended versions of the datasets:
https://broadinstitute.github.io/2023_12_JUMP_data_only_vignettes/howto/tutorial_basic.html

**Comment by afermg** [comment]
It is! I made sure of that last week. Shantanu double-checked [here](https://broadinstitute.slack.com/archives/C01AF25CQLT/p1714580548777319?thread_ts=1714580483.804619&cid=C01AF25CQLT). The one thing that may still change is the newest CRISPR profile that Niranj produced. I am still waiting for the link on that one though. I generally try to keep the links to the minimum, so in case of doubt 
[](https://broadinstitute.github.io/2023_12_JUMP_data_only_vignettes/howto/tutorial_basic.html) is the correct one.

**Comment by afermg** [comment]
> On [this page](https://broadinstitute.github.io/2023_12_JUMP_data_only_vignettes/explanations/FAQ.html) it says Data
> 
> Does JUMP contain X compound/gene? We have done our best to ensure that if you can check if your compound is available [here](https://github.com/jump-cellpainting/datasets/issues).
> 
> but that URL just goes to the issues of this repo rather than a place to check for your compound/gene.
> 
> (side note: typo in "Frequently Asqued Questions" in the sidebar -> Asked)

Many thanks for pointing those issues out! The repeated thing indicates a search-and-replace gone wrong. I've fixed all these issues now. The Question links to [broad.io/babel](broad.io/babel) webtool (which is our closest thing to a knowledge graph atm) and also to the [metadata files](https://github.com/jump-cellpainting/datasets/tree/main/metadata).

**Comment by afermg** [comment]
> (if it will be hard to commit to keeping it up to date, we could instead put a big warning here that says go here [URL] to find the latest location of the latest profiles to use)

It will be a challenge, but as far as I understand we expect the profiles to be settled soon. The notebook in that tutorial is run in the background at every commit, so I (or whoever is in charge after me) will get notified if it fails. I think these commits solve the issues. Many thanks for double-checking Anne! that's loads of help. I will close the issue to focus on the other ones but feel free to reopen it if you find something out of place.

**Comment by niranjchandrasekaran** [comment]
> The one thing that may still change is the newest CRISPR profile that Niranj produced. I am still waiting for the link on that one though.

@afermg the newest CRISPR profile is the one that you are already using (the one that Shantanu confirmed on Slack). You are all set when it comes to using the latest ORF and CRISPR profiles.

**Comment by afermg** [comment]
Then we are good to go. Thanks @niranjchandrasekaran!
