### ISSUE TITLE
Using the data

### ISSUE THREAD

**Issue by ethancohen123** [jump-cellpainting/datasets#12]
Hi,
Thanks for this awesome work !
I'm starting to look at the data and I have a couple questions. As I understand, the cpg016 is not fully released yet but the other ones are. In order to have a better understanding and start to get used to the data and structure I am planning to use the cpg012 from Bray et al. Could you please provide me indications to start working with it ? I would like to know how to download the data (or stream it if possible) , how to apply the illumination function and QC process and if there is a metadata file (as in the ones in the BBBC022 for example) with name of compounds, plate id , image path 1 to 5 etc ?

Thank you very much for your help !

**Comment by niranjchandrasekaran** [comment]
Hi Ethan,

Thanks for your interest in our datasets! 

> In order to have a better understanding and start to get used to the data and structure I am planning to use the cpg012 from Bray et al.

If you would like to use a smaller dataset to get started, I recommend `cpg0000`. It has fewer plates than `cpg0012` and it has the advantage of being subdivided into multiple sub-experiments; each sub-experiment can be considered a complete dataset. For more details, please check out this repo – https://github.com/jump-cellpainting/2021_Chandrasekaran_submitted.

> I would like to know how to download the data (or stream it if possible) , how to apply the illumination function and QC process and if there is a metadata file (as in the ones in the BBBC022 for example) with name of compounds, plate id , image path 1 to 5 etc ?

The repo for `cpg0000` contains answers to most of your questions. If you have additional questions, please feel free to reach out via issues on that repo.
