### ISSUE TITLE
Missing SMILES data and request for additional metadata for pert_iname, pubchem_cid and gene

### ISSUE THREAD

**Issue by MLMatcha** [jump-cellpainting/datasets#131]
I recently downloaded the metadata for compounds (metadata/compound.csv.gz) and noticed that the SMILES column is missing. 

Also, I was wondering if you have the perturbation name, PubChem ID and gene?

**Comment by niranjchandrasekaran** [comment]
We had mistakenly removed the SMILES from the compound metadata file. We are [currently adding it back](https://github.com/jump-cellpainting/datasets/pull/125) to the file. If you would like to download the updated file before the pull request is merged, you can find it here: https://github.com/jump-cellpainting/datasets/blob/e5e20e73df0067bff48076d1c437259503f6aa60/metadata/compound.csv.gz

> Also, I was wondering if you have the perturbation name, PubChem ID and gene?

We don't have the perturbation name and PubChem ID, but we are working on making the gene target annotations available for a subset of the compounds.

**Comment by MLMatcha** [comment]
Thank you for the information provided, much appreciated!
