### ISSUE TITLE
Compressed images?

### ISSUE THREAD

**Issue by jasperhyp** [jump-cellpainting/datasets#143]
Hi! Thanks for sharing this resource and the extensive documentations. In the Cell Painting Gallery [website](https://broadinstitute.github.io/cellpainting-gallery/machine_learning.html), a path to the compressed images was provided (`cpg0016-jump/SOURCE/workspace/segmentation/cellpose/objects/BATCH/`). However, there is no such path in the AWS S3 bucket (inspecting the Quilt browser). How could I possibly obtain such compressed images? Thank you! 

Cross-posted [issue](https://github.com/broadinstitute/cellpainting-gallery/issues/107) in CPG repo.

**Comment by ErinWeisbart** [comment]
They have been uploaded for source_8 and the uploads for other sources are in progress.
(Granular details are available in https://github.com/broadinstitute/cellpainting-gallery/issues/73 though I will note in this issue as well when all of the uploads have completed)
Thanks for your patience.

**Comment by afermg** [comment]
@ErinWeisbart I was running my [jump_portrait](https://github.com/broadinstitute/monorepo/tree/main/libs/jump_portrait) tests and I noticed that the imagis for which Adit tested the compression flags were only in the staging bucket. Should I open an issue to keep track of which sources' compressed images are public? Thanks!

**Comment by ErinWeisbart** [comment]
@afermg I think the "compressed images" that you're talking about are different than what Jasper is talking about.
The path that Jasper references above are the images that Tim is currently uploading to staging. They are within the workspace folder.

I see in staging right now that within the images folder there are "images_compressed" folders in staging `s3://staging-cellpainting-gallery/cpg0016-jump/SOURCE/images/BATCH/images_compressed/`) and I think this is what you're talking about. I don't know anything about those images so perhaps @shntnu can answer when those images will be made public?
