### ISSUE TITLE
question of cpg0012

### ISSUE THREAD

**Issue by liujunhongznn** [jump-cellpainting/datasets#18]
we didn't found the compound data in cpg0012, where shall we get the compounds?

**Comment by niranjchandrasekaran** [comment]
Hi @liujunhongznn, the identity of compounds in `cpg0012` are in s3://cellpainting-gallery/cpg0012-wawer-bioactivecompoundprofiling/broad/workspace/metadata/external_metadata/cdrp_compounds.tsv

Please let me know if you have any other questions about this dataset.

**Comment by liujunhongznn** [comment]
@niranjchandrasekaran thank! I will take a look.
