### ISSUE TITLE
how to get bucket name and endpoints?

### ISSUE THREAD

**Issue by dark-flash** [jump-cellpainting/datasets#20]
Thank you for sharing this great dataset! Now we want to make a copy of this dataset on another cloud, but we found this error: endpoint and bucket not match, and we use the bucket : arn:aws:s3:::cellpainting-gallery, endpoint:https://dataexchange.us-east-1.amazonaws.com. Could you point the correct endpoint and bucket name? Thank you very much!

**Comment by niranjchandrasekaran** [comment]
Hi @dark-flash, thanks for your interest in our dataset! I am tagging @shntnu who can help you.

**Comment by shntnu** [comment]
@dark-flash Unfortunately, I have no clue about endpoints
Does it help to know that you can browse the bucket via
https://cellpainting-gallery.s3.amazonaws.com/index.html
and download individual files like this?
https://cellpainting-gallery.s3.amazonaws.com/cpg0016-jump/source_4/workspace/structure/structure.json

> we want to make a copy of this dataset on another cloud

Would you be comfortable sharing why you would like to do this vs. accessing it directly from S3? The continuation of AWS’s generous support of our project depends on the usage of the dataset, with access tracked at https://broad.io/cpgdash. It would be fantastic if you could continue to access it directly, but of course, you are welcome (and allowed, per the open license) to do what you’d like :)

Thanks again for your interest in our dataset!
