### ISSUE TITLE
2020_11_04_CPJUMP1 (cpg0000-jump-pilot) dataset

### ISSUE THREAD

**Issue by AlaaBessadok** [jump-cellpainting/datasets#23]
Hello, I would like to download the dataset cpg0000-jump-pilot to work on the 300+ compounds. My question is where to find the name of the compounds (is there a csv file for that) and is there an information about cell death modality induced by those 300+compounds (such as necrosis, apoptosis)? Many thanks in advance!

**Comment by niranjchandrasekaran** [comment]
Hi @AlaaBessadok, you can find the names of the compounds [here](https://github.com/jump-cellpainting/JUMP-Target/blob/master/JUMP-Target-1_compound_metadata.tsv). We don't have any cell death annotations, but these compounds are from Broad's drug repurposing hub. You can browse [this site](https://clue.io/repurposing-app) to find additional annotations and links to external databases which may have cell death annotations.
