### ISSUE TITLE
Are all compounds/genes from cpg0000 replicated in cpg0016?

### ISSUE THREAD

**Issue by nmra-abarthmaron** [jump-cellpainting/datasets#38]
I see `cpg0016` has a 119 `TARGET2` plates, and 4 `TARGET1` plates. But when I query by `InChIKey` there are only 182 compounds in common.
```
>>> compound = pd.read_csv("metadata/compound.csv.gz")
>>> pilot_md = pd.read_csv('JUMP-Target/JUMP-Target-2_compound_metadata.tsv', sep='\t')
>>> len(set(pilot_md['InChIKey']) & set(compound['Metadata_InChIKey']))
182
```
So it seems that 124 compounds are not being identified. Are the `cpg0016` TARGET1/2 plates different form the `cpg0000` target1/2 plates?

As for ORFs, I found that only `'HPGDS', 'HRH4', 'KCNJ1', 'KCNN4', 'MME', 'MMP2', 'S1PR2'` were present in cpg0000 but missing from cpg0016. Were some of the cpg0016 plates `JUMP-Target-ORF` plates?
Thanks!

**Comment by niranjchandrasekaran** [comment]
Hi @nmra-abarthmaron, the `InChIKey`s in `cpg0016` were generated after standardizing `SMILES` which resulted in them changing a little bit. Here is the mapping from Target2 `InChIKey` to the `JCP_ID` in `cpg0016` that should help you map the `cpg0016` Target1/Target2 plates to that of `cpg0000`: https://gist.github.com/niranjchandrasekaran/2247451fd7b6e111abe6277b3705a458.

> I found that only 'HPGDS', 'HRH4', 'KCNJ1', 'KCNN4', 'MME', 'MMP2', 'S1PR2' were present in cpg0000 but missing from cpg0016.

This matches my understanding that seven genes are missing in `cpg0016`. 

> Were some of the cpg0016 plates JUMP-Target-ORF plates?

Apart from the seven genes, all the other genes from `JUMP-Target-ORF` should be present in `cpg0016`, but not on the same plate as we didn't run any `JUMP-Target-ORF` plates while creating `cpg0016`.

**Comment by nmra-abarthmaron** [comment]
Thank you, this is very helpful!
