### ISSUE TITLE
Question regarding the illumination correction

### ISSUE THREAD

**Issue by dpaysan** [jump-cellpainting/datasets#40]
Dear JUMP team,

I have a brief question regarding the illumination correction of cpg0016 for source 4.
Do you have used the same methodology (i.e. the same CellProfiler pipeline) to compute the illumination correction function given as a .npy file in the image directories as described in Rohban et al., 2017 and Bray et al. 2016?
Additionally, I was wondering if the images were only corrected for the uneven illumination before nuclei and cells were segmented and their morphological profiles computed for cpg0016 source 4?
Also to obtain the corrected illumination images the raw images were simply divided by the illumination correction function, right?

Thanks a million in advance for the clarifications and also for working on this outstanding data set generation and curation effort!

**Comment by niranjchandrasekaran** [comment]
Hi @dpaysan, thanks for your interest in our dataset. I am tagging @bethac07 and @ErinWeisbart who can answer your questions about illumination correction.

**Comment by ErinWeisbart** [comment]
The exact pipelines used for all of image processing can be found [here](https://github.com/broadinstitute/imaging-platform-pipelines/tree/master/JUMP_production). It is the same kind of correction in those papers, most recently described [here](https://www.biorxiv.org/content/10.1101/2022.07.13.499171v2).
I believe that all sources performed the flat field illumination correction before segmentation and measurements.
Yes, the raw images were divided by the .npy correction functions.

**Comment by dpaysan** [comment]
Thanks so much! That helps a lot. Seems like the illumination pipeline is largely the same with the exception of the additional resizing steps for the optimized protocol and the adjusted Median filter size (20 in the optimized vs 200 before).

Excited to see this tremendous effort and data set to continue to develop!
