### ISSUE TITLE
Question regarding the planned profile normalization for cpg0016

### ISSUE THREAD

**Issue by dpaysan** [jump-cellpainting/datasets#60]
Dear JUMP-CP team,

thanks a lot for the great data resource.
I was wondering if you could briefly comment on the planned normalization of the profiles to (partially) mitigate batch effects for the ORF data. Since the treatment conditions are only partially repeated, I assume you plan to normalize the profiles with respect to the batch-specific (respectively plate-specific) negative controls as described [here]( https://carpenter-singh-lab.broadinstitute.org/blog/how-normalize-cell-painting-data), right? Which negative control setting would you use for that -  BFP, eGFP, HcRed, Luciferase or LacZ?

Thanks a lot in advance for your help!

**Comment by niranjchandrasekaran** [comment]
Hi Daniel,

We typically negative control normalization to control for plate-to-plate variations. In the case of the ORF plates, we are currently using all four negative controls – BFP, HcRed, Luciferase or LacZ. For compound plates, we will be using DMSO for normalization. Regarding batch effects, the normalization strategies mentioned in the blog post that you linked, work to an extent, but they don't remove batch effects completely. We are using other methods from the world of transcriptomics to correct batch effects. We are working on a manuscript and will soon be able to share the details as well as the batch corrected profiles.

**Comment by dpaysan** [comment]
Sounds great! That helps a lot. Looking forward to reading the manuscript!
