### ISSUE TITLE
Create FAQ for the resource

### ISSUE THREAD

**Issue by shntnu** [jump-cellpainting/datasets#62]
I'll start this thread for collating FAQs. To get started, let's link out to issues that seem like good additions to the FAQ-to-be

**Comment by shntnu** [comment]
https://github.com/jump-cellpainting/megamap/issues/8

**Comment by shntnu** [comment]
Clarify that for some plates, we have images but not anything else downstream. These plates failed QC but we kept them because they may be useful for developing QC methods.

https://github.com/jump-cellpainting/datasets/issues/72#issuecomment-1999460135

**Comment by shntnu** [comment]
@afermg this is the FAQ issue I mentioned during checkin

**Comment by afermg** [comment]
@shntnu Is the goal to translate these into an actual FAQ or just to link them?

**Comment by shntnu** [comment]
> @shntnu Is the goal to translate these into an actual FAQ or just to link them?

Translate them to an actual FAQ in the JUMP handbook, then close out this issue because we should track it in that repo instead (via PR's each time there is a new Q). What do you think?

**Comment by afermg** [comment]
Sounds good to me

**Comment by afermg** [comment]
I think this is solved by [broad.io/jump](broad.io/jump). I'll close this issue but LMK if there is anything else to be done.

**Comment by shntnu** [comment]
> I think this is solved by [broad.io/jump](https://broad.io/jump). I'll close this issue but LMK if there is anything else to be done.

The FAQ itself is currently at this location
https://broadinstitute.github.io/2023_12_JUMP_data_only_vignettes/explanations/FAQ.html
