### ISSUE TITLE
Not able to find cp001 in cp-gallery

### ISSUE THREAD

**Issue by MaryFllh** [jump-cellpainting/datasets#64]
Hello, 
I am trying to download the four JUMP datasets, and looking at https://cellpainting-gallery.s3.amazonaws.com/index.html I see a number of folders with "jump" but not sure if they relate to the four datasets mentioned in the README. 
My assumption is that there should be four directories with names cpg0000-jump, cpg0002-jump, cpg0002-jump and cpg0016 as the principle dataset. However, I see `cpg0000-jump-pilot/, cpg0002-jump-scope/,  cpg0014-jump-adipocyte/, cpg0016-jump-fixed/, cpg0016-jump/, dev-cpg0016-jump/, test-cpg0016-jump/ and jump/`.("jump/" is not accessible) 
Can you please clarify which folders correspond to the four jump datasets and how can i only download the images please?

Thank you!

**Comment by niranjchandrasekaran** [comment]
Hi @MaryFllh,

The four folders that you are looking for are 
 
- `cpg0016-jump`
- `cpg0000-jump-pilot`
- `cpg0001-jump-cellpainting-protocol`
- `cpg0002-jump-scope`

The remaining folders are mostly temp folders.

**Comment by MaryFllh** [comment]
Thank you for clarifying.
