### ISSUE TITLE
Release SMILES strings

### ISSUE THREAD

**Issue by wongdanr** [jump-cellpainting/datasets#86]
Hello @shntnu! I noticed that for a lot of the compounds in metadata/compound.csv, there are no corresponding SMILES strings that can be found on PubChem. Is it possible to provide another column for SMILES? Thank you!

**Comment by shntnu** [comment]
@wongdanr We are working on this via this internal issue https://github.com/jump-cellpainting/datasets-private/issues/77. We will report back once this is ready

**Comment by ChenyuWang-Monica** [comment]
Could you also provide a column of the source map, i.e. which source the compound is nominated by? Thanks!

**Comment by shntnu** [comment]
> Hello @shntnu! I noticed that for a lot of the compounds in metadata/compound.csv, there are no corresponding SMILES strings that can be found on PubChem. Is it possible to provide another column for SMILES? Thank you!

Done in #103 


> Could you also provide a column of the source map, i.e. which source the compound is nominated by? Thanks!

Done in #106
